### ISSUE TITLE
Error in code 

### ISSUE THREAD

**Issue by aqibfayyaz** [nbertagnolli/counsel-chat#4]
when i try to run utils_test.py file i get this error
ERROR: test_sample_candidates (__main__.UtilsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "utils_test.py", line 19, in test_sample_candidates
    df = pd.DataFrame(data, columns=["questionID", "answerText", 'split'])
  File "/home/aqib/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 468, in __init__
    raise ValueError('DataFrame constructor not properly called!')
ValueError: DataFrame constructor not properly called!

**Comment by nbertagnolli** [comment]
Did this happen when running the interaction script in the container?  Try building the docker container with `make build` then running the interaction with `make interact`

**Comment by nbertagnolli** [comment]
Did this work for you?

**Comment by aqibfayyaz** [comment]
yes make build worked successfully after you added the missing docker folder but i do not know how to use make interact? convai image has been successfully build

**Comment by nbertagnolli** [comment]
When you run `make interact` in your terminal what happens?
