### ISSUE TITLE
Error in running code

### ISSUE THREAD

**Issue by chetnakhanna16** [nbertagnolli/counsel-chat#6]
Thank you for your detailed explanation. I am trying to replicate your results to understand how I can perform transfer learning on convai model.  However, after cloning this repo I am unable to run the code using the below script. Actually, the GitHub repo doesn't have the train.py file.
`python3 train.py --dataset_path counsel_chat_250-tokens.json --gradient_accumulation_steps=4 --lm_coef=2.0 --max_history=1 --n_epochs=3 --num_candidates=4 --train_batch_size=2`

If I am running this script using the hugging face repo and modifying the code which you mentioned in the blog, I keep on getting one or the other error. 

Since I want to look at the code and play around with it, I am not running this chunk of code:
```
make build
make interact CHECKPOINT_DIR=counselchat_convai
```
Thank you in advance.

**Comment by chetnakhanna16** [comment]
This is the error I get when I train the convai model on counsel-chat data using the training parameters given by you in the blog.

```
ERROR:ignite.engine.engine.Engine:Current run is terminating due to exception: can't multiply sequence by non-int of type 'float'
ERROR:ignite.engine.engine.Engine:Engine run is terminating due to exception: can't multiply sequence by non-int of type 'float'
Traceback (most recent call last):
  File "train.py", line 268, in <module>
    train()
  File "train.py", line 260, in train
    trainer.run(train_loader, max_epochs=args.n_epochs)
  File "/Users/ankurrastogi/opt/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 702, in run
    return self._internal_run()
  File "/Users/ankurrastogi/opt/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 775, in _internal_run
    self._handle_exception(e)
  File "/Users/ankurrastogi/opt/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 469, in _handle_exception
    raise e
  File "/Users/ankurrastogi/opt/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 745, in _internal_run
    time_taken = self._run_once_on_dataset()
  File "/Users/ankurrastogi/opt/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 850, in _run_once_on_dataset
    self._handle_exception(e)
  File "/Users/ankurrastogi/opt/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 469, in _handle_exception
    raise e
  File "/Users/ankurrastogi/opt/anaconda3/lib/python3.7/site-packages/ignite/engine/engine.py", line 833, in _run_once_on_dataset
    self.state.output = self._process_function(self, self.state.batch)
  File "train.py", line 183, in update
    loss = (lm_loss * args.lm_coef + mc_loss * args.mc_coef) / args.gradient_accumulation_steps
TypeError: can't multiply sequence by non-int of type 'float'
```

**Comment by nbertagnolli** [comment]
I've added the training file that I used : ).  I just ran it locally using transformers 3.3.1 and it worked for me.  Let me know if you run into any problems : ).  Sorry I forgot to include the training file!

**Comment by nbertagnolli** [comment]
I'm going to close this issue for now since it's running on my machine.  Let me know if you're still having problems and I'm happy to help take a look : )
